[version]
path = "src/discobase/__about__.py"

[build.targets.sdist]
only-include = ["src/discobase/"]

[build.targets.wheel]
packages = ["src/discobase/"]

[envs.hatch-test]
installer = "pip"
dependencies = [
  "coverage[toml]~=7.4",
  "pytest~=8.1",
  "pytest-asyncio~=0.23"
]

[envs.hatch-test.scripts]
run = "pytest{env:HATCH_TEST_ARGS:} {args} -s"
run-cov = "coverage run -m pytest{env:HATCH_TEST_ARGS:} {args}"
cov-combine = "coverage combine"
cov-report = "coverage report"

[envs.docs]
dependencies = ["mkdocs", "mkdocstrings[python]", "mkdocs-material"]

[envs.docs.scripts]
build = "mkdocs build --clean"
serve = "mkdocs serve"
