site_name: Discobase
site_url: https://discobase.zintensity.dev
repo_url: https://github.com/ZeroIntensity/discobase
repo_name: ZeroIntensity/discobase

nav:
    - Home: index.md
    - Core Library: library.md
    - Discord Interface: discord_interface.md
    - Demonstration: demonstration.md
    - API Reference: reference.md

theme:
    name: material
    logo: assets/discobase_white.png
    palette:
        - media: "(prefers-color-scheme)"
          primary: black
          accent: black
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: black
          accent: black
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          accent: black
          toggle:
              icon: material/brightness-4
              name: Switch to system preference
    features:
        - content.tabs.link
        - content.code.copy
        - content.action.edit
        - search.highlight
        - search.share
        - search.suggest
        - navigation.footer
        - navigation.indexes
        - navigation.sections
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
        - toc.follow

    icon:
        repo: fontawesome/brands/github

markdown_extensions:
    - attr_list
    - md_in_html
    - toc:
          permalink: true
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.tabbed:
          alternate_style: true

plugins:
    - search
    - mkdocstrings:
          handlers:
              python:
                  paths: [src]
                  options:
                      show_root_heading: true
                      show_object_full_path: false
                      show_symbol_type_heading: true
                      show_symbol_type_toc: true
                      show_signature: true
                      seperate_signature: true
                      show_signature_annotations: true
                      signature_crossrefs: true
                      show_source: true
                      show_if_no_docstring: true
                      show_docstring_examples: true
