name: Tests

on:
    push:
        branches:
            - main
        paths:
            - src/discobase/**
    pull_request:
        branches:
            - main
        paths:
            - src/discobase/**

concurrency:
    group: test-${{ github.head_ref }}
    cancel-in-progress: true

env:
    PYTHONUNBUFFERED: "1"
    FORCE_COLOR: "1"
    TEST_BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}

jobs:
    run-container-matrix:
        name: Test matrix on Linux
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Python 3.12
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12"

            - name: Install Hatch
              run: pip install --upgrade hatch

            - name: Run tests in matrix
              run: hatch test --all
